import { WeatherIconEntry } from "../types/weatherIconEntry";

export const weatherIcons: WeatherIconEntry[] = [
  { code: 0, name: "Clear sky", icon: "☀️" },
  { code: 1, name: "Mainly clear", icon: "🌤️" },
  { code: 2, name: "Partly cloudy", icon: "🌥️" },
  { code: 3, name: "Overcast", icon: "☁️" },
  { code: 45, name: "Fog", icon: "🌫️" },
  { code: 48, name: "Depositing rime fog", icon: "🌫️" },
  { code: 51, name: "Light drizzle", icon: "🌦️" },
  { code: 53, name: "Moderate drizzle", icon: "🌦️" },
  { code: 55, name: "Dense drizzle", icon: "🌧️" },
  { code: 56, name: "Light freezing drizzle", icon: "🌧️" },
  { code: 57, name: "Dense freezing drizzle", icon: "🌧️" },
  { code: 61, name: "Slight rain", icon: "🌦️" },
  { code: 63, name: "Moderate rain", icon: "🌧️" },
  { code: 65, name: "Heavy rain", icon: "🌧️" },
  { code: 66, name: "Light freezing rain", icon: "🌧️" },
  { code: 67, name: "Heavy freezing rain", icon: "🌧️" },
  { code: 71, name: "Slight snow fall", icon: "❄️" },
  { code: 73, name: "Moderate snow fall", icon: "❄️" },
  { code: 75, name: "Heavy snow fall", icon: "❄️" },
  { code: 77, name: "Snow grains", icon: "🌨️" },
  { code: 80, name: "Slight rain showers", icon: "🌦️" },
  { code: 81, name: "Moderate rain showers", icon: "🌧️" },
  { code: 82, name: "Violent rain showers", icon: "🌧️" },
  { code: 85, name: "Slight snow showers", icon: "❄️" },
  { code: 86, name: "Heavy snow showers", icon: "❄️" },
  { code: 95, name: "Thunderstorm (slight or moderate)", icon: "⛈️" },
  { code: 96, name: "Thunderstorm with slight hail", icon: "⛈️" },
  { code: 99, name: "Thunderstorm with heavy hail", icon: "⛈️" },
];
